spring:
   profiles:
     active: dev
   application:
     name: app
   jpa:
     open-in-view: false
server:
  servlet:
    context-path:
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus,httptrace
  endpoint:
    health:
      show-details: always