version: '3.9'


services:
  app:
    container_name: orderservice
    ports:
      - '8080:8080'
    restart: always
    build:
      context: .
    depends_on:
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
  loki:
    image: grafana/loki:2.8.2
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml:ro
    ports:
      - "3100:3100"

  promtail:
      image: grafana/promtail:2.8.2
      volumes:
        - /var/log:/var/log:ro
        - ./promtail/config.yml:/etc/promtail/config.yml:ro
      command: -config.file=/etc/promtail/config.yml